# Carga de aeropuertos (DM_AEROPUERTOS)

### Partimos del ficheros __aero.csv__

In [97]:
import pandas as pd
import numpy as np

### Cargamos la extensión SQL:

In [98]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

### Conexión a __MySQL__ BBDD __local__

In [99]:
# Windows/teacher local enviroment

%sql mysql+pymysql://root:root@localhost/dw_aero

(pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['mysql+pymysql://root:***@localhost/DW_AERO'])

In [100]:
# linux local enviroment
# %sql mysql+pymysql://root:admin123@localhost/DW_AERO

In [101]:
from sqlalchemy import create_engine

# Windows/teacher local enviroment
conn = create_engine("mysql+pymysql://root:root@localhost/dw_aero")

In [102]:
# from sqlalchemy import create_engine

# Linux/local enviroment
# conn = create_engine("mysql+pymysql://root:admin123@localhost/DW_AERO")

In [103]:
conn

Engine(mysql+pymysql://root:***@localhost/DW_AERO)

In [104]:
%sql show tables

 * mysql+pymysql://root:***@localhost/DW_AERO
6 rows affected.

[('CO_RUTAS_EQUIPAMIENTOS',),
 ('DM_AEROLINEAS',),
 ('DM_AEROPUERTOS',),
 ('DM_EQUIPAMIENTOS',),
 ('DM_PAIS',),
 ('HC_RUTAS',)]

### Comprobamos los datos de la tabla DM_AEROPUERTOS

In [105]:
%sql select * from DM_AEROPUERTOS

 * mysql+pymysql://root:***@localhost/DW_AERO
0 rows affected.

[]

### Lectura del fichero aeropuertos.csv

In [106]:
# Windows/teacher enviroment
df_grupo3_aeroports = pd.read_csv("input\\aeropuertos.csv",  sep=',', header='infer')
df_grupo3_aeroports.head(10)

FileNotFoundError: [Errno 2] No such file or directory: 'input\\aeropuertos.csv'

In [107]:
# Linux/local enviroment
# df_grupo3_aeroports = pd.read_csv("input//aeropuertos.csv",  sep=',', header='infer')
# df_grupo3_aeroports.head(10)

,cod_aeropuerto,cod_pais,nombre_aeropuerto,ciudad_aeropuerto,pais_aeropuerto,cod_iata_faa,cod_icao,latitud,longitud,altitud,zona_horaria,dst,zona_horaria_tz
0,0001,PNG,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282.0,10.0,U,Pacific/Port_Moresby
1,0002,PNG,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.788700,20.0,10.0,U,Pacific/Port_Moresby
2,0003,PNG,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388.0,10.0,U,Pacific/Port_Moresby
3,0004,PNG,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239.0,10.0,U,Pacific/Port_Moresby
4,0005,PNG,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.220050,146.0,10.0,U,Pacific/Port_Moresby
5,0006,PNG,Wewak Intl,Wewak,Papua New Guinea,WWK,AYWK,-3.583828,143.669186,19.0,10.0,U,Pacific/Port_Moresby
6,0007,GRL,Narsarsuaq,Narssarssuaq,Greenland,UAK,BGBW,61.160517,-45.425978,112.0,-3.0,E,America/Godthab
7,0008,GRL,Nuuk,Godthaab,Greenland,GOH,BGGH,64.190922,-51.678064,283.0,-3.0,E,America/Godthab
8,0009,GRL,Sondre Stromfjord,Sondrestrom,Greenland,SFJ,BGSF,67.016969,-50.689325,165.0,-3.0,E,America/Godthab
9,0010,GRL,Thule Air Base,Thule,Greenland,THU,BGTL,76.531203,-68.703161,251.0,-4.0,E,America/Thule

### Revisión de nulos

In [108]:
for col in df_grupo3_aeroports.columns:
    print("Revisando nulos: ", col)
    print(df_grupo3_aeroports[col].isnull().sum())

Revisando nulos:  cod_aeropuerto
0
Revisando nulos:  cod_pais
0
Revisando nulos:  nombre_aeropuerto
0
Revisando nulos:  ciudad_aeropuerto
0
Revisando nulos:  pais_aeropuerto
0
Revisando nulos:  cod_iata_faa
2
Revisando nulos:  cod_icao
1
Revisando nulos:  latitud
1
Revisando nulos:  longitud
1
Revisando nulos:  altitud
1
Revisando nulos:  zona_horaria
1
Revisando nulos:  dst
1
Revisando nulos:  zona_horaria_tz
1

### Revisión de nulos en col 'cod_iata_faa'

In [109]:
df_grupo3_aeroports[ df_grupo3_aeroports['cod_iata_faa'].isnull()]

,cod_aeropuerto,cod_pais,nombre_aeropuerto,ciudad_aeropuerto,pais_aeropuerto,cod_iata_faa,cod_icao,latitud,longitud,altitud,zona_horaria,dst,zona_horaria_tz
22,0023,CAN,Shearwater,Halifax,Canada,NaN,CYAW,44.639721,-63.499444,167.0,-4.0,A,America/Halifax
297,0300,BEL,Beauvechain,Beauvechain,Belgium,NaN,EBBE,50.758610,4.768333,370.0,1.0,E,Europe/Brussels

### Reemplazo nulos cod_iata_faa (3 pos - Z99)

In [110]:
df_grupo3_aeroports['cod_iata_faa'] = df_grupo3_aeroports['cod_iata_faa'].fillna('Z99')

### Revisión de nulos en col 'cod_icao'

In [111]:
df_grupo3_aeroports[ df_grupo3_aeroports['cod_icao'].isnull()]

,cod_aeropuerto,cod_pais,nombre_aeropuerto,ciudad_aeropuerto,pais_aeropuerto,cod_iata_faa,cod_icao,latitud,longitud,altitud,zona_horaria,dst,zona_horaria_tz
6916,8345,USA,Montgomery Field,San Diego,United States,MYF,NaN,32.4759,117.759,17.0,8.0,A,Asia/Chongqing

### Reemplazo nulos cod_icao (4 pos - Z999)

In [112]:
df_grupo3_aeroports['cod_icao'] = df_grupo3_aeroports['cod_icao'].fillna('Z999')

### Comprobaciones integridad país

### Para realizar la comprobación de integridad consultamos los datos de países en bd

In [113]:
t_pais = %sql select cod_pais as cod_pais_p, pais from DM_PAIS

 * mysql+pymysql://root:***@localhost/DW_AERO
244 rows affected.

In [114]:
df_grupo3_pais = t_pais.DataFrame()
df_grupo3_pais.head(5)

  cod_pais_p         pais
0        ABW        Aruba
1        AFG  Afghanistan
2        AGO       Angola
3        AIA     Anguilla
4        ALB      Albania

### Cruce aeropuerto - paises

In [115]:
df_grupo3_aeroports.head(5)

,cod_aeropuerto,cod_pais,nombre_aeropuerto,ciudad_aeropuerto,pais_aeropuerto,cod_iata_faa,cod_icao,latitud,longitud,altitud,zona_horaria,dst,zona_horaria_tz
0,0001,PNG,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282.0,10.0,U,Pacific/Port_Moresby
1,0002,PNG,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.788700,20.0,10.0,U,Pacific/Port_Moresby
2,0003,PNG,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388.0,10.0,U,Pacific/Port_Moresby
3,0004,PNG,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239.0,10.0,U,Pacific/Port_Moresby
4,0005,PNG,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.220050,146.0,10.0,U,Pacific/Port_Moresby

In [116]:
df_grupo3_aeroports_merged = pd.merge(left=df_grupo3_aeroports, right=df_grupo3_pais,
                      how='left', left_on='cod_pais', right_on='cod_pais_p')

In [117]:
df_grupo3_aeroports_merged.head(10)

,cod_aeropuerto,cod_pais,nombre_aeropuerto,ciudad_aeropuerto,pais_aeropuerto,cod_iata_faa,cod_icao,latitud,longitud,altitud,zona_horaria,dst,zona_horaria_tz,cod_pais_p,pais
0,0001,PNG,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea
1,0002,PNG,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.788700,20.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea
2,0003,PNG,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea
3,0004,PNG,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea
4,0005,PNG,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.220050,146.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea
5,0006,PNG,Wewak Intl,Wewak,Papua New Guinea,WWK,AYWK,-3.583828,143.669186,19.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea
6,0007,GRL,Narsarsuaq,Narssarssuaq,Greenland,UAK,BGBW,61.160517,-45.425978,112.0,-3.0,E,America/Godthab,GRL,Greenland
7,0008,GRL,Nuuk,Godthaab,Greenland,GOH,BGGH,64.190922,-51.678064,283.0,-3.0,E,America/Godthab,GRL,Greenland
8,0009,GRL,Sondre Stromfjord,Sondrestrom,Greenland,SFJ,BGSF,67.016969,-50.689325,165.0,-3.0,E,America/Godthab,GRL,Greenland
9,0010,GRL,Thule Air Base,Thule,Greenland,THU,BGTL,76.531203,-68.703161,251.0,-4.0,E,America/Thule,GRL,Greenland

In [118]:
df_grupo3_aeroports_merged[df_grupo3_aeroports_merged['cod_pais_p'].isnull()]

,cod_aeropuerto,cod_pais,nombre_aeropuerto,ciudad_aeropuerto,pais_aeropuerto,cod_iata_faa,cod_icao,latitud,longitud,altitud,zona_horaria,dst,zona_horaria_tz,cod_pais_p,pais
1151,1173,SSD,Juba,Juba,South Sudan,JUB,HSSJ,4.872006,31.601117,1513.0,3.0,U,Africa/Juba,NaN,NaN
6248,7674,WAK,Wake Island Afld,Wake island,Wake Island,AWK,PWAK,19.282067,166.636444,14.0,12.0,U,Pacific/Wake,NaN,NaN
7855,9290,SSD,Torit,Torit,South Sudan,Z99,HSTR,4.411111,32.578889,2018.0,3.0,N,Africa/Juba,NaN,NaN

### Reemplazo nulos cod_pais_p (3 pos - Z99)

In [119]:
df_grupo3_aeroports_merged['cod_pais_p'] = df_grupo3_aeroports_merged['cod_pais_p'].fillna('Z99')

### Añadimos una nueva columna: Concatenar 'cod_aeropuerto' +  'cod_pais'

In [120]:
df_grupo3_aeroports_merged['JDL'] = df_grupo3_aeroports_merged['cod_aeropuerto'] + ' ' + df_grupo3_aeroports_merged['cod_pais_p']

In [121]:
df_grupo3_aeroports_merged.head(5)

,cod_aeropuerto,cod_pais,nombre_aeropuerto,ciudad_aeropuerto,pais_aeropuerto,cod_iata_faa,cod_icao,latitud,longitud,altitud,zona_horaria,dst,zona_horaria_tz,cod_pais_p,pais,JDL
0,0001,PNG,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea,0001 PNG
1,0002,PNG,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.788700,20.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea,0002 PNG
2,0003,PNG,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea,0003 PNG
3,0004,PNG,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea,0004 PNG
4,0005,PNG,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.220050,146.0,10.0,U,Pacific/Port_Moresby,PNG,Papua New Guinea,0005 PNG

## Volcado del df a la bd

Nos quedamos con a estructura definitiva:     
COD_AEROPUERTO VARCHAR(4) NOT NULL,
NOMBRE_AEROPUERTO VARCHAR(100) NOT NULL,
CIUDAD_AEROPUERTO VARCHAR(45) NULL,
PAIS_AEROPUERTO VARCHAR(45) NULL,
COD_PAIS VARCHAR(3) NULL,
COD_IATA_FAA VARCHAR(3) NULL,
COD_ICAO VARCHAR(4) NULL,
LATITUD DECIMAL(14,8) NULL,
LONGITUD DECIMAL(14,8) NULL,
ALTITUD DECIMAL(14,8) NULL,
ZONA_HORARIA INT NULL,
DST VARCHAR(1) NULL,
ZONA_HORARIA_TZ VARCHAR(45) NULL

### Seleccion de columnas

In [122]:
df_grupo3_aeroports_to_database = df_grupo3_aeroports_merged.drop(['cod_pais_p','pais', 'JDL'],1)

/tmp/ipykernel_5332/3185017211.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_grupo3_aeroports_to_database = df_grupo3_aeroports_merged.drop(['cod_pais_p','pais', 'JDL'],1)

### Volcado a BBDD

In [123]:
df_grupo3_aeroports_to_database.to_sql('DM_AEROPUERTOS', con = conn, if_exists = 'append', index=False)

### Comprobaciones conteos

In [124]:
count_df_grupo3 = df_grupo3_aeroports_to_database.count()
count_df_grupo3

cod_aeropuerto       8108
cod_pais             8108
nombre_aeropuerto    8108
ciudad_aeropuerto    8108
pais_aeropuerto      8108
cod_iata_faa         8108
cod_icao             8108
latitud              8107
longitud             8107
altitud              8107
zona_horaria         8107
dst                  8107
zona_horaria_tz      8107
dtype: int64

In [125]:
count_tab = %sql select count(*) from DM_AEROPUERTOS
count_tab

 * mysql+pymysql://root:***@localhost/DW_AERO
1 rows affected.

[(8108,)]

### Comprobaciones de la carga

In [126]:
%sql select * from DM_AEROPUERTOS where cod_pais = 'ESP'

 * mysql+pymysql://root:***@localhost/DW_AERO
84 rows affected.

[('1051', 'Fuerteventura', 'Fuerteventura', 'Spain', 'ESP', 'FUE', 'GCFV', Decimal('28.45271700'), Decimal('-13.86376100'), Decimal('83.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('1052', 'Hierro', 'Hierro', 'Spain', 'ESP', 'VDE', 'GCHI', Decimal('27.81484700'), Decimal('-17.88705600'), Decimal('103.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('1053', 'La Palma', 'Santa Cruz De La Palma', 'Spain', 'ESP', 'SPC', 'GCLA', Decimal('28.62647800'), Decimal('-17.75561100'), Decimal('107.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('1054', 'Gran Canaria', 'Gran Canaria', 'Spain', 'ESP', 'LPA', 'GCLP', Decimal('27.93188600'), Decimal('-15.38658600'), Decimal('78.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('1055', 'Lanzarote', 'Las Palmas', 'Spain', 'ESP', 'ACE', 'GCRR', Decimal('28.94546400'), Decimal('-13.60522500'), Decimal('47.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('1056', 'Tenerife Sur', 'Tenerife', 'Spain', 'ESP', 'TFS', 'GCTS', Decimal('28.04447500'), Decimal('-16.57248900'), Decimal('209.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('1057', 'Tenerife Norte', 'Tenerife', 'Spain', 'ESP', 'TFN', 'GCXO', Decimal('28.48265300'), Decimal('-16.34153600'), Decimal('2073.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('1058', 'Melilla', 'Melilla', 'Spain', 'ESP', 'MLN', 'GEML', Decimal('35.27981700'), Decimal('-2.95625600'), Decimal('156.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1211', 'Albacete', 'Albacete', 'Spain', 'ESP', 'Z99', 'LEAB', Decimal('38.94852800'), Decimal('-1.86351700'), Decimal('2302.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1212', 'Alicante', 'Alicante', 'Spain', 'ESP', 'ALC', 'LEAL', Decimal('38.28216900'), Decimal('-0.55815600'), Decimal('142.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1213', 'Almeria', 'Almeria', 'Spain', 'ESP', 'LEI', 'LEAM', Decimal('36.84393600'), Decimal('-2.37009700'), Decimal('70.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1214', 'Asturias', 'Aviles', 'Spain', 'ESP', 'OVD', 'LEAS', Decimal('43.56356700'), Decimal('-6.03462200'), Decimal('416.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1215', 'Cordoba', 'Cordoba', 'Spain', 'ESP', 'ODB', 'LEBA', Decimal('37.84200600'), Decimal('-4.84887800'), Decimal('297.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1216', 'Bilbao', 'Bilbao', 'Spain', 'ESP', 'BIO', 'LEBB', Decimal('43.30109700'), Decimal('-2.91060800'), Decimal('138.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1218', 'Barcelona', 'Barcelona', 'Spain', 'ESP', 'BCN', 'LEBL', Decimal('41.29707800'), Decimal('2.07846400'), Decimal('12.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1219', 'Talavera La Real', 'Badajoz', 'Spain', 'ESP', 'BJZ', 'LEBZ', Decimal('38.89125000'), Decimal('-6.82133300'), Decimal('609.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1220', 'A Coruna', 'La Coruna', 'Spain', 'ESP', 'LCG', 'LECO', Decimal('43.30206100'), Decimal('-8.37725600'), Decimal('326.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1221', 'Armilla', 'Granada', 'Spain', 'ESP', 'Z99', 'LEGA', Decimal('37.13322200'), Decimal('-3.63569400'), Decimal('2297.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1222', 'Girona', 'Gerona', 'Spain', 'ESP', 'GRO', 'LEGE', Decimal('41.90096900'), Decimal('2.76054700'), Decimal('468.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1223', 'Granada', 'Granada', 'Spain', 'ESP', 'GRX', 'LEGR', Decimal('37.18873100'), Decimal('-3.77735600'), Decimal('1860.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1224', 'Getafe', 'Madrid', 'Spain', 'ESP', 'Z99', 'LEGT', Decimal('40.29413900'), Decimal('-3.72383300'), Decimal('2029.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1225', 'Ibiza', 'Ibiza', 'Spain', 'ESP', 'IBZ', 'LEIB', Decimal('38.87285800'), Decimal('1.37311700'), Decimal('20.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1226', 'Jerez', 'Jerez', 'Spain', 'ESP', 'XRY', 'LEJR', Decimal('36.74462200'), Decimal('-6.06011100'), Decimal('93.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1227', 'Murcia San Javier', 'Murcia', 'Spain', 'ESP', 'MJV', 'LELC', Decimal('37.77497200'), Decimal('-0.81238900'), Decimal('11.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1229', 'Barajas', 'Madrid', 'Spain', 'ESP', 'MAD', 'LEMD', Decimal('40.49355600'), Decimal('-3.56676400'), Decimal('2000.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1230', 'Malaga', 'Malaga', 'Spain', 'ESP', 'AGP', 'LEMG', Decimal('36.67490000'), Decimal('-4.49910600'), Decimal('52.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1231', 'Menorca', 'Menorca', 'Spain', 'ESP', 'MAH', 'LEMH', Decimal('39.86259700'), Decimal('4.21864700'), Decimal('298.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1232', 'Moron Ab', 'Sevilla', 'Spain', 'ESP', 'OZP', 'LEMO', Decimal('37.17491700'), Decimal('-5.61594400'), Decimal('285.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1233', 'Ocana', 'Ocana', 'Spain', 'ESP', 'Z99', 'LEOC', Decimal('39.93750000'), Decimal('-3.50333300'), Decimal('2405.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1234', 'Pamplona', 'Pamplona', 'Spain', 'ESP', 'PNA', 'LEPP', Decimal('42.77003900'), Decimal('-1.64633100'), Decimal('1504.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1235', 'Alcantarilla', 'Murcia', 'Spain', 'ESP', 'Z99', 'LERI', Decimal('37.95111100'), Decimal('-1.23031900'), Decimal('250.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1236', 'Reus', 'Reus', 'Spain', 'ESP', 'REU', 'LERS', Decimal('41.14739200'), Decimal('1.16717200'), Decimal('234.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1237', 'Rota Ns', 'Rota', 'Spain', 'ESP', 'Z99', 'LERT', Decimal('36.64521100'), Decimal('-6.34945800'), Decimal('86.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1238', 'Salamanca', 'Salamanca', 'Spain', 'ESP', 'SLM', 'LESA', Decimal('40.95211700'), Decimal('-5.50198600'), Decimal('2595.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1239', 'Son Bonet', 'Son Bonet', 'Spain', 'ESP', 'Z99', 'LESB', Decimal('39.59888900'), Decimal('2.70277800'), Decimal('135.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1240', 'Palma De Mallorca', 'Palma De Mallorca', 'Spain', 'ESP', 'Z99', 'LESJ', Decimal('39.55167500'), Decimal('2.73880800'), Decimal('27.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1241', 'San Luis', 'San Luis', 'Spain', 'ESP', 'Z99', 'LESL', Decimal('39.86222200'), Decimal('4.25833300'), Decimal('197.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1242', 'San Sebastian', 'San Sebastian', 'Spain', 'ESP', 'EAS', 'LESO', Decimal('43.35651900'), Decimal('-1.79061100'), Decimal('15.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1243', 'Santiago', 'Santiago', 'Spain', 'ESP', 'SCQ', 'LEST', Decimal('42.89633300'), Decimal('-8.41514400'), Decimal('1213.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1244', 'Seo De Urgel', 'Seo De Urgel', 'Spain', 'ESP', 'LEU', 'LESU', Decimal('42.33861100'), Decimal('1.40916700'), Decimal('2625.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1245', 'Torrejon', 'Madrid', 'Spain', 'ESP', 'TOJ', 'LETO', Decimal('40.49674700'), Decimal('-3.44587200'), Decimal('2026.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1246', 'Valencia', 'Valencia', 'Spain', 'ESP', 'VLC', 'LEVC', Decimal('39.48931400'), Decimal('-0.48162500'), Decimal('225.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1247', 'Valladolid', 'Valladolid', 'Spain', 'ESP', 'VLL', 'LEVD', Decimal('41.70611100'), Decimal('-4.85194400'), Decimal('2775.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1248', 'Cuatro Vientos', 'Madrid', 'Spain', 'ESP', 'Z99', 'LEVS', Decimal('40.37067800'), Decimal('-3.78514400'), Decimal('2267.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1249', 'Vitoria', 'Vitoria', 'Spain', 'ESP', 'VIT', 'LEVT', Decimal('42.88283600'), Decimal('-2.72446900'), Decimal('1682.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1250', 'Vigo', 'Vigo', 'Spain', 'ESP', 'VGO', 'LEVX', Decimal('42.23180000'), Decimal('-8.62677500'), Decimal('855.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1251', 'Santander', 'Santander', 'Spain', 'ESP', 'SDR', 'LEXJ', Decimal('43.42706400'), Decimal('-3.82000600'), Decimal('16.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1252', 'Zaragoza Ab', 'Zaragoza', 'Spain', 'ESP', 'ZAZ', 'LEZG', Decimal('41.66624200'), Decimal('-1.04155300'), Decimal('863.00000000'), 1, 'E', 'Europe/Madrid'),
 ('1253', 'Sevilla', 'Sevilla', 'Spain', 'ESP', 'SVQ', 'LEZL', Decimal('37.41800000'), Decimal('-5.89310600'), Decimal('111.00000000'), 1, 'E', 'Europe/Madrid'),
 ('3998', 'Son Sant Joan', 'Palma de Mallorca', 'Spain', 'ESP', 'PMI', 'LEPA', Decimal('39.55361000'), Decimal('2.72777800'), Decimal('24.00000000'), 1, 'E', 'Europe/Madrid'),
 ('5659', 'La Gomera Airport', 'La Gomera', 'Spain', 'ESP', 'GMZ', 'GCGM', Decimal('28.02960000'), Decimal('-17.21460000'), Decimal('718.00000000'), 0, 'E', 'Atlantic/Canary'),
 ('5661', 'Ceuta Heliport', 'Ceuta', 'Spain', 'ESP', 'JCU', 'GECT', Decimal('35.89690000'), Decimal('-5.29908000'), Decimal('0E-8'), 1, 'E', 'Europe/Madrid'),
 ('5781', 'Logroño-Agoncillo Airport', 'Logroño-Agoncillo', 'Spain', 'ESP', 'RJL', 'LELO', Decimal('42.45420000'), Decimal('-2.32083000'), Decimal('1161.00000000'), 1, 'E', 'Europe/Madrid'),
 ('6488', 'Ronda Airport', 'Ronda', 'Spain', 'ESP', 'RRA', 'Z999', Decimal('36.75000000'), Decimal('-5.16666700'), Decimal('2500.00000000'), 1, 'E', 'Europe/Madrid'),
 ('6756', 'Leon Airport', 'Leon', 'Spain', 'ESP', 'LEN', 'LELN', Decimal('42.58900000'), Decimal('-5.65555600'), Decimal('3006.00000000'), 1, 'E', 'Europe/Madrid'),
 ('6757', 'Burgos Airport', 'Burgos', 'Spain', 'ESP', 'RGS', 'LEBG', Decimal('42.35762800'), Decimal('-3.62076400'), Decimal('2945.00000000'), 1, 'E', 'Europe/Madrid'),
 ('6868', 'Sabadell Airport', 'Sabadell', 'Spain', 'ESP', 'QSA', 'LELL', Decimal('41.52090000'), Decimal('2.10508000'), Decimal('0E-8'), 1, 'E', 'Europe/Madrid'),
 ('6902', 'Ronda', 'Ronda', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('36.73333000'), Decimal('-5.16666700'), Decimal('1000.00000000'), 1, 'U', 'Europe/Madrid'),
 ('7459', 'Lleida-Alguaire Airport', 'Lleida', 'Spain', 'ESP', 'ILD', 'LEDA', Decimal('41.72777800'), Decimal('0.53583300'), Decimal('1148.00000000'), 1, 'E', 'Europe/Madrid'),
 ('7488', 'Huesca-Pirineos Airport', 'Huesca', 'Spain', 'ESP', 'HSK', 'LEHC', Decimal('42.08083300'), Decimal('-0.32333300'), Decimal('1768.00000000'), 1, 'U', 'Europe/Madrid'),
 ('7489', 'Ciudad Real Central Airport', 'Ciudad Real', 'Spain', 'ESP', 'CQM', 'LERL', Decimal('38.85638900'), Decimal('-3.97000000'), Decimal('636.00000000'), 1, 'U', 'Europe/Madrid'),
 ('7731', 'La Cerdanya', 'Das i Fontanals de Cerdanya', 'Spain', 'ESP', 'Z99', 'LECD', Decimal('42.38640000'), Decimal('1.86670000'), Decimal('3586.00000000'), 1, 'E', 'Europe/Madrid'),
 ('7740', 'Barcelona Cruise Terminal', 'Barcelona', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('41.35890100'), Decimal('2.17844700'), Decimal('0E-8'), 1, 'E', 'Europe/Madrid'),
 ('7742', 'Lanzarote Arrecife Cruise Terminal', 'Arrecife Lanzarote', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('28.96729800'), Decimal('-13.52752800'), Decimal('0E-8'), 0, 'E', 'Atlantic/Canary'),
 ('7743', 'Tenerife Cruise Terminal', 'Santa Cruz de Tenerife', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('28.47006800'), Decimal('-16.24247100'), Decimal('0E-8'), 0, 'E', 'Atlantic/Canary'),
 ('7745', 'Malaga Cruise Terminal', 'Malaga', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('36.70298900'), Decimal('-4.41395000'), Decimal('0E-8'), 1, 'E', 'Europe/Madrid'),
 ('7747', 'Vigo Cruise Terminal', 'Vigo', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('42.24153700'), Decimal('-8.72879900'), Decimal('0E-8'), 1, 'E', 'Europe/Madrid'),
 ('7753', 'Cadiz Cruise Terminal', 'Cadiz', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('36.53482100'), Decimal('-6.29064900'), Decimal('0E-8'), 1, 'E', 'Europe/Madrid'),
 ('7967', 'Tarifa', 'Tarifa', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('36.07078100'), Decimal('-5.60276400'), Decimal('20.00000000'), 1, 'E', 'Europe/Madrid'),
 ('8261', 'Algeciras Heliport', 'Algeciras', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('36.12888900'), Decimal('-5.44111100'), Decimal('98.00000000'), 1, 'E', 'Europe/Madrid'),
 ('8262', 'Algeciras Heliport', 'Algeciras', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('36.12888900'), Decimal('-5.44111100'), Decimal('98.00000000'), 1, 'E', 'Europe/Madrid'),
 ('8690', 'Fuentemilanos Airport', 'Segovia', 'Spain', 'ESP', 'Z99', 'LEFM', Decimal('40.88923300'), Decimal('-4.23947800'), Decimal('3284.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9484', 'Santa Justa', 'Sevilla', 'Spain', 'ESP', 'Z99', 'SVSJ', Decimal('37.39205100'), Decimal('-5.97513500'), Decimal('23.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9485', 'Cordoba Station', 'Cordoba', 'Spain', 'ESP', 'Z99', 'CRDB', Decimal('37.88857300'), Decimal('-4.78917700'), Decimal('390.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9486', 'Granada Station', 'Granada', 'Spain', 'ESP', 'Z99', 'GRND', Decimal('37.18405500'), Decimal('-3.60916000'), Decimal('2421.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9487', 'Atocha', 'Madrid', 'Spain', 'ESP', 'Z99', 'MDAT', Decimal('40.40750000'), Decimal('-3.69166700'), Decimal('2188.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9493', 'Toledo Railway Station', 'Toledo', 'Spain', 'ESP', 'Z99', 'TLDO', Decimal('39.86236300'), Decimal('-4.01108300'), Decimal('1736.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9494', 'Chamartin Station', 'Madrid', 'Spain', 'ESP', 'Z99', 'MADC', Decimal('40.47227200'), Decimal('-3.68215000'), Decimal('2188.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9495', 'Abando', 'Bilbao', 'Spain', 'ESP', 'Z99', 'BLBO', Decimal('43.25947000'), Decimal('-2.92901700'), Decimal('62.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9496', 'Aeroport', 'Barcelona', 'Spain', 'ESP', 'Z99', 'ARPT', Decimal('41.28843600'), Decimal('2.07240900'), Decimal('39.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9497', 'Passeig de Gracia', 'Barcelona', 'Spain', 'ESP', 'Z99', 'PGRC', Decimal('41.39218600'), Decimal('2.16482000'), Decimal('39.00000000'), 1, 'U', 'Europe/Madrid'),
 ('9498', 'Sants', 'Barcelona', 'Spain', 'ESP', 'Z99', 'BSNT', Decimal('41.37935900'), Decimal('2.14047400'), Decimal('39.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9499', 'Railway Station', 'Figueres', 'Spain', 'ESP', 'Z99', 'FGRS', Decimal('42.26506500'), Decimal('2.96882200'), Decimal('128.00000000'), 1, 'E', 'Europe/Madrid'),
 ('9534', 'Algerciras Port', 'Algerciras', 'Spain', 'ESP', 'Z99', 'Z999', Decimal('36.13600000'), Decimal('-5.43500000'), Decimal('0E-8'), 1, 'E', 'Europe/Madrid')]